name: kuvia
description: A new Flutter project.
version: 1.0.6    # 版本命名只可以是0-9，两位数的不允许, 更改此处时与build.gradle文件的versionName同步, common AppConfig的appVersion

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_vector_icons: ^0.2.1
  flustars: ^0.2.6
  dio: ^2.1.0
  rxdart: ^0.21.0
  cached_network_image: ^1.1.1
  url_launcher: ^5.0.2
  pull_to_refresh: ^1.4.8
  # device_info: ^0.4.0+1
  video_player: ">=0.7.0 <0.11.0"
  screen: ">=0.0.4 <0.1.0"
  fluttertoast: ^3.1.0
  tip_dialog: ^2.0.1
  event_bus: ^1.1.0
  firebase_core: ^0.4.0
  firebase_messaging: ^5.0.4

  #图片画廊组件相关引用
  http_client_helper: ^0.2.0
  crypto: ^2.0.6
  image_picker_saver:
    git:
      https://github.com/cnhefang/image_picker_saver.git
  image_picker: ^0.6.0+17
  flutter_facebook_login: ^3.0.0
  share_extend: ^1.0.8
  
  google_sign_in: ^4.0.1+3
  uni_links: ^0.2.0

  connectivity: ^0.4.3+6
  notification_permissions: ^0.4.0
  introduction_screen:
    git: 
        url: https://github.com/telinx/introduction_screen.git
  package_info: ^0.4.0+6
  flutter_staggered_grid_view: ^0.3.0
  webview_flutter: ^0.3.14+1
  vibration: ^1.2.2
  flutter_statusbar_text_color: ^0.1.2
  xml2json: ^4.1.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
    - assets/images/

    

  